apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-game-deployment
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: tic-tac-toe-game
        image: puneet1/tic_tac_toe 
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
